### ISSUE TITLE
ROSBridge replacement

### ISSUE THREAD

**Issue by reinzor** [eclipse-zenoh/zenoh-ts#53]
Thanks for developing this library!

We are investigating how we can use the remote API plugin together with `zenoh-ts` to communicate with our ROS network via the browser instead of [ROSBridge](https://github.com/RobotWebTools/rosbridge_suite) or [Foxglove ROS Bridge](https://docs.foxglove.dev/docs/connecting-to-data/ros-foxglove-bridge/). 

The solutions mentioned above serialize ROS messages from and to JSON within the bridge so that it easy for the web client to work with these messages without depending on message definition files. Also [this library exists](https://www.npmjs.com/package/@foxglove/rosmsg) for message serialization and deserialization to work with ROS serialized messages. 

What are your thought about message serialization to/from JSON within the remote API plugin. Would this be possible at some point by a ROS specific plugin? Would love to hear your thoughts about this.

Thanks

**Comment by Mallets** [comment]
Zenoh is agnostic to the actual payload and schema, serialization, and deserialization of data belongs to application logic.
In other terms, Zenoh sends and receives bytes.

Being the TypeScript API a general purpose API for Zenoh and not related specifically to ROS2, I'd say to directly use the the existing ROS serialization library. Moreover, I believe sending ROS-encoded messages on the wire is more efficient than sending JSON messages. Does it make sense?

**Comment by reinzor** [comment]
This definitely makes sense, thanks.
