### ISSUE TITLE
clarify z_get_liveliness example

### ISSUE THREAD

**Issue by milyin** [eclipse-zenoh/zenoh-ts#63]
This piece of code
```ts
 let receiver = session.liveliness().get(key_expr, {timeout: seconds.of(20)});

  if (!(receiver instanceof Receiver)){
    return // Return in case of callback get query
  }

  let reply = await receiver.receive();
```
is unclear. The `get` may return undefined value if callback passed to the options. But in this example this never happens and it makes user wonder why this check is required.

Better to add e.g `as Receiver` to first `let` expression

**Comment by Charles-Schleich** [comment]
Added Explicit Receiver in https://github.com/eclipse-zenoh/zenoh-ts/pull/73
